baseURL = "https://hidexir.github.io/"
languageCode = "ja"
title = "hidexir"
theme="hidexir"
publishDir="docs"

[Params]
nickname = "hidexir"
profile = "https://avatars1.githubusercontent.com/u/26104151?s=460&u=0cd68b1b5f2fbb1940bfac368db17898675b9baf&v=4"
github = "https://github.com/hidexir"
twitter = "https://twitter.com/hidexir"
